[battery]
disabled = false


[memory_usage]
threshold = -1
disabled = false
format = "[${ram} ${ram_pct}]($style) "


[ruby]
disabled = true


[python]
disabled = true
pyenv_version_name = true
format = '[${symbol}${virtualenv} ]($style)'

[gcloud]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = true


[directory]
truncation_length = 5

[status]
style = "bg:blue"
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[cmd_duration]
min_time = 500
show_milliseconds = true
format = '[${duration}]($style) '
disabled = false

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+2"
time_range = "10:00:00-14:00:00"

[kubernetes]
format = '[($symbol$context)](blue) '
disabled = false

[docker_context]
disabled = true

[helm]
disabled = true

[package]
disabled = true
