name: Nix Formatting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nixfmt
      run: |
        shopt -s globstar
        FILES=$(echo **/*.nix)
        echo $FILES
        nix-shell -p nixfmt-rfc-style --run "nixfmt -c $FILES"
        echo $?
